plugins:
  issue_comment.created:
    - uses:
        - plugin: ubq-testing/ubiquibot-ask-plugin:compute.yml@development
          name: Research
          id: research-command
          type: github
          description: "Query GPT-4 direct from issues and pull requests."
          command: "/research"
          example: "/research The spec for this issue is unclear. Can you explain it in simpler terms?"
          with:
            keys:
              openAi: "" # this is a secret, so only install this plugin config in your private org config repo
            disabledCommands: []
