name: Deploy to Cloudflare Pages

on:
  push:

jobs:
  deploy-to-cloudflare:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Check Cloudflare API Token
        run: |
          if [[ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]]; then
            echo "CLOUDFLARE_API_TOKEN secret must be set" >&2
            exit 1
          fi
      - name: Deploy to Cloudflare
        uses: ubiquity/cloudflare-deploy-action@main
        with:
          cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          repository: ${{ github.repository }}
          production_branch: ${{ github.event.repository.default_branch }}
          output_directory: "static"
          is_production: ${{ github.event_name == 'push' && github.ref == 'refs/heads/${{ github.event.repository.default_branch }}' }}
        # env:
        # Add any environment variables you need to pass along here
        #   SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        #   SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
